### ISSUE TITLE
Missing msvcr120.dll in windows x64 archive

### ISSUE THREAD

**Issue by martinberanek** [yandex-qatools/postgresql-embedded#21]
Running on Windows 7 64bit, during startup I got:
```
XII 03, 2015 10:51:38 DOP. ru.yandex.qatools.embed.postgresql.PostgresProcess onAfterProcessStart
SEVERE: Failed to read PID file (File 'C:\Users\beranekm\AppData\Local\Temp\postgresql-embed-c4f7a4b4-b9cb-4cc1-a622-2de8305deff2\db-content-e5264bb1-3489-4280-982d-8e892a4580db\postmaster.pid' does not exist)
Exception in thread "main" java.lang.NullPointerException
	at Main.main(Main.java:23)
Failed to extract file set: java.lang.NullPointerException
XII 03, 2015 10:51:39 DOP. ru.yandex.qatools.embed.postgresql.PostgresProcess stopInternal
INFO: trying to stop postgresql
```

after investigation, i find out, that binaries need ```msvcr12.dll``` which is not in archive (postgresql-9.4.4-1-windows-x64-binaries.zip)

the strange is, that this library is in ```c:\Windows\SysWOW64\msvcr120.dll```

how can I solve this problem, what are you recommend?

**Comment by smecsia** [comment]
@martinberanek From what you can get on google: 

**"The program can't start because MSVCR120.dll is missing from your computer. Try reinstalling the program to fix this problem."**
If you get that error, download the Visual C++ Redistributable Packages for Visual Studio 2013:
 http://www.microsoft.com/en-us/download/details.aspx?id=40784. 
The vcredist_x86.exe you will need if you are running the 32-bit version of PostgreSQL 9.4 and the vcredist_x64.exe is generally the one you want if you are running the 64-bit PostgreSQL 9.4beta1.

I'm not sure this will help, but you can try anyway.

**Comment by Tapac** [comment]
MSVCR120.dll comes with jre 1.8, so all you need to do is extend 'Path' environment variable in onBeforeProcessStart with jre\bin.
Something like this (in Kotlin) :

```kotlin
override fun onBeforeProcessStart(processBuilder: ProcessBuilder?, config: PostgresConfig?, runtimeConfig: IRuntimeConfig?) {
            super.onBeforeProcessStart(processBuilder, config, runtimeConfig)
            processBuilder?.environment()?.let { env ->
                env["Path"] = env["Path"].orEmpty() + ";${env["JAVA_HOME"]!!}\\jre\\bin"
     }
}
```

**Comment by smecsia** [comment]
@Tapac thank you for the suggestion. I'll try to use it a bit later.
Btw it would be great if you could send the PR (but not in Kotlin :) ).

**Comment by smecsia** [comment]
I'm closing this one, since there's no answer. Feel free to reopen if it's still actual.
